name: Build and Push Docker Image

on:
  # Trigger on pushes to main branch
  push:
    branches: [ main, master ]
  # Trigger on new releases/tags
  release:
    types: [ published ]
  # Allow manual trigger
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKERHUB_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for GHCR
      id: meta-ghcr
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # set latest tag for main/master branch only
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          # set full version tag for releases (1.0.0, 1.0.1, etc.)
          type=semver,pattern={{version}}

    - name: Extract metadata for Docker Hub
      id: meta-dockerhub
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository }}
        tags: |
          # set latest tag for main/master branch only
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          # set full version tag for releases (1.0.0, 1.0.1, etc.)
          type=semver,pattern={{version}}

    - name: Build and push to both registries
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta-ghcr.outputs.tags }}
          ${{ steps.meta-dockerhub.outputs.tags }}
        labels: ${{ steps.meta-ghcr.outputs.labels }}